name: Deploy OSX

on:
  push:
    tags:
      - v*
      - o*

jobs:
  deploy-osx:
    env:
      REPOSITORY_NAME: JuceWithActions
      BUILD_DIRECTORY: cmake-build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          cmake -B ${BUILD_DIRECTORY}
          cmake --build ${BUILD_DIRECTORY} --target ${JuceWithActions}_All

      - name: Packaging
        run: |
          chmod 755 bin/packaging.sh
          ./bin/packaging.sh osx "${BUILD_DIRECTORY}/${REPOSITORY_NAME}_artefacts/Release" "${REPOSITORY_NAME}"

      - name: Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pkg/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
